@extends('layouts.default')
@section('content')
        <section id="content">
          <section class="hbox stretch">
            <aside class="aside-md bg-white b-r" id="subNav">
              <div class="wrapper b-b header">Commission Manager</div>
              <ul class="nav">
                <li class="b-b b-light"><a href="/invoice"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Pending Commission</a></li>
                <li class="b-b b-light"><a href="/payments"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Processed Commission</a></li>
              </ul>
            </aside>
            <aside>
              <section class="vbox">
                <header class="header bg-white b-b clearfix">
                  <div class="row m-t-sm">
                    <div class="col-sm-8 m-b-xs">
                      <a href="#subNav" data-toggle="class:hide" class="btn btn-sm btn-default active"><i class="fa fa-caret-right text fa-lg"></i><i class="fa fa-caret-left text-active fa-lg"></i></a>
                      <a href="#" data-toggle="modal" class="btn btn-sm btn-default"><i class="fa fa-upload"></i> Upload</a>
                      <a href="#" data-toggle="modal" class="btn btn-sm btn-default"><i class="fa fa-file"></i> File</a>
                    <a href="#" data-toggle="modal" class="btn btn-sm btn-default"><i class="fa fa-print"></i> Print List</a>
                   <span class="badge badge-info">Record(s) Found : {{ $bills->total() }} {{ str_plural('Commission', $bills->total()) }} </span> 
                    </div>

                  <form action="/" method="GET">
                    <div class="col-sm-4 m-b-xs">
                      <div class="input-group">
                        <input type="text" name='search' id='search' class="input-sm form-control" placeholder="Search for a client">
                        <span class="input-group-btn">
                          <button class="btn btn-sm btn-default" type="submit">Go!</button>
                        </span>
                      </div>
                    </div>
                     </form>
                    </div>
                  </div>
                </header>
                <section class="scrollable wrapper w-f">
                  <section class="panel panel-default">
                    <div class="table-responsive">
                      <table class="table table-striped m-b-none text-sm" width="100%">
                        <thead>
                          <tr>
                            
                            <th width="20"></th>
                            <th width="20"></th>
                            <th>Invoice #</th>
                            <th>Customer</th>
                            <th>Date</th>
                            <th>Invoice Sum</th>
                            <th>Commission Rate</th>
                            <th>Commission Amount</th>
                            <th>Tax</th>
                            <th>Commission Receivable</th>
                            <th>Status</th>
                            <th>Generated By</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                       @foreach( $bills as $bill )
                          <tr>
                             <td><a onclick="makepayment('{{ $bill->id  }}')" class="bootstrap-modal-form-open" href="#make_payment" data-toggle="modal" ><i class="fa fa-money"></i></a></td>
                             <td><a href="/print-invoice/{{ $bill->id }}" data-toggle="modal" ><i class="fa fa-print"></i></a></td>
                            <td>{{ $bill->invoice_number }}</td>
                            <td>{{ $bill->account_name }}</td>
                            <td>{{ $bill->created_on }}</td>
                            <td>{{ $bill->currency }}{{ $bill->amount }}</td>
                            <td>{{ $bill->commission_rate }}</td>
                            <td>{{ $bill->amount * ($bill->commission_rate/100) }}</td>
                            <td>{{ (($bill->amount * ($bill->commission_rate/100)) * 5/100) }}</td>
                            <td>{{ ($bill->amount * ($bill->commission_rate/100)) - (($bill->amount * ($bill->commission_rate/100)) * 5/100) }}</td>
                            <td>{{ $bill->status }}</td>
                            <td>{{ $bill->created_by }}</td>
                          </tr>
                         @endforeach 
                        </tbody>
 
                      </table>
                    </div>
                  </section>
                </section>
                <footer class="footer bg-white b-t">
                  <div class="row text-center-xs">
                    <div class="col-md-6 hidden-sm">
                      <p class="text-muted m-t">
                      </p>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right text-center-xs">                
                     
                         {!!$bills->render()!!} 
                        
                    </div>
                  </div>
                </footer>
              </section>
            </aside>
          </section>
          <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a>
        </section>
@stop






  


  




