@extends('layouts.default')
@section('content')
        <section id="content">
          <section class="hbox stretch">
            <aside class="aside-md bg-white b-r" id="subNav">
              <div class="wrapper b-b header">Commission Manager</div>
              <ul class="nav">
                <li class="b-b b-light"><a href="/commission"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Commission Receivable</a></li>
                <li class="b-b b-light"><a href="#"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Processed Commission</a></li>
              </ul>
            </aside>
            <aside>
              <section class="vbox">
                <header class="header bg-white b-b clearfix">
                  <div class="row m-t-sm">
                    <div class="col-sm-8 m-b-xs">
                      <a href="#subNav" data-toggle="class:hide" class="btn btn-sm btn-default active"><i class="fa fa-caret-right text fa-lg"></i><i class="fa fa-caret-left text-active fa-lg"></i></a>
                      <a href="#" data-toggle="modal" class="btn btn-sm btn-default"><i class="fa fa-upload"></i> Upload</a>
                      <a href="#" data-toggle="modal" class="btn btn-sm btn-default"><i class="fa fa-file"></i> File</a>
                    <a href="#" data-toggle="modal" class="btn btn-sm btn-default"><i class="fa fa-print"></i> Print List</a>
                   <span class="badge badge-info">Record(s) Found : {{ $bills->total() }} {{ str_plural('Commission', $bills->total()) }} </span>
                    </div>

                  <form action="/find-commission" method="GET">
                    <div class="col-sm-4 m-b-xs">
                      <div class="input-group">
                        <input type="text" name='search' id='search' class="input-sm form-control" placeholder="Search for a commission">
                        <span class="input-group-btn">
                          <button class="btn btn-sm btn-default" type="submit">Go!</button>
                        </span>
                      </div>
                    </div>
                     </form>
                    </div>
                  </div>
                </header>
                <section class="scrollable wrapper w-f">
                  <section class="panel panel-default">
                    <div class="table-responsive">
                      <table class="table table-striped m-b-none text-sm" width="100%">
                        <thead>
                          <tr>
                            
                            
                            <th></th>
                            <th>Customer</th>
                            <th>Product</th>
                            <th>Insurer</th>
                            <th>Date</th>
                            <th>Currency</th>
                            <th>Premium</th>
                            <th>Commission Rate</th>
                            <th>Commission Receivable</th>
                            <th>Premium Status</th>
                            <th>Generated By</th>
                            <th>Commission Status</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                       @foreach( $bills as $keys => $bill )
                          <tr>
                       
                            <td>{{ ++$keys }}</td>
                            <td>{{ $bill->account_name }}</td>
                            <td>{{ $bill->policy_product }}</td>
                            <td>{{ $bill->policy_insurer }}</td>
                            <td>{{ $bill->created_on }}</td>
                            <td>{{ $bill->currency }}</td>
                            <td>{{ $bill->amount }}</td>
                            <td>{{ $bill->commission_rate }}</td>
                            @if($bill->policy_product=='Motor Insurance')
                           {{--  <td>{{ (($bill->amount * ($bill->commission_rate/100))-$stickercharge) }}</td>
                            <td>{{ ((($bill->amount * ($bill->commission_rate/100))-$stickercharge) * $broker_tax_rate/100) }}</td> --}}
                            <td>{{ (($bill->amount * ($bill->commission_rate/100))-$stickercharge) - ((($bill->amount * ($bill->commission_rate/100))-$stickercharge) * $broker_tax_rate/100) }}</td>
                            @else
                             {{-- <td>{{ ($bill->amount * ($bill->commission_rate/100)) }}</td>
                            <td>{{ (($bill->amount * ($bill->commission_rate/100)) * $broker_tax_rate/100) }}</td> --}}
                            <td>{{ ($bill->amount * ($bill->commission_rate/100)) - (($bill->amount * ($bill->commission_rate/100)) * $broker_tax_rate/100) }}</td>
                            @endif
                            <td>{{ $bill->status }}</td>
                            <td>{{ $bill->created_by }}</td>
                            @if($bill->commission == 'Pending')
                            <td><a href="#edit_modal_consult" class="btn btn-s-md btn-danger btn-rounded bootstrap-modal-form-open" onclick="saveCommission('{{ $bill->id }}','{{ $bill->account_name }}')"  id="edit" name="edit" data-toggle="modal" alt="edit">Pending</a></td>
                            @else
                             <td><a href="#edit_modal_consult" class="btn btn-s-md btn-success btn-rounded bootstrap-modal-form-open" onclick=""  id="edit" name="edit" data-toggle="modal" alt="edit">Paid</a></td>

                            @endif

                          </tr>
                         @endforeach 
                        </tbody>
 
                      </table>
                    </div>
                  </section>
                </section>
                <footer class="footer bg-white b-t">
                  <div class="row text-center-xs">
                    <div class="col-md-6 hidden-sm">
                      <p class="text-muted m-t">
                      </p>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right text-center-xs">                
                     
                         {!!$bills->render()!!} 
                        
                    </div>
                  </div>
                </footer>
              </section>
            </aside>
          </section>
          <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a>
        </section>
@stop

<script type="text/javascript">
  
  function saveCommission(id,name)
  {

  swal({
  title: "Commission Received for " + name +"!",
  text: "Enter commission amount:",
  type: "input",
  showCancelButton: true,
  closeOnConfirm: false,
  animation: "slide-from-top",
  inputPlaceholder: "Enter amount"
},
function(inputValue){
  if (inputValue === false) return false;
  
  if (inputValue === "") {
    swal.showInputError("You need to enter commission received amount!");
    return false
  }
  
  else
  {
    $.get('/process-commission',
          {
             "ID": id,
             "amountpaid": inputValue  
          },
          function(data)
          { 
            
            $.each(data, function (key, value) 
            {
            if(value == "OK")
            {
              swal("Paid!", name +" was successfully processed.", "success"); 
              location.reload(true);
             }
            else
            { 
              swal("Failed", name +" failed to process.", "error");
              
            }
           
        });
                                          
          },'json');    
  }
});

}


</script>



  


  




